<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="styleforpages.css">
</head>
<body>
    <header>Java Exceptions - Try...Catch</header>
    <section><p><h2>Java Exceptions</h2>
        When executing Java code, different errors can occur: coding errors made by the programmer, errors due to wrong input, or other unforeseeable things.
        
        When an error occurs, Java will normally stop and generate an error message. The technical term for this is: Java will throw an exception (throw an error).
        
        <h2>Java try and catch</h2>
        The try statement allows you to define a block of code to be tested for errors while it is being executed.
        
        The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
        
        The try and catch keywords come in pairs:
        <br>
        Syntax
        <pre>
        try {
          //  Block of code to try
        }
        catch(Exception e) {
          //  Block of code to handle errors
        }</pre>
        Consider the following example:
        <br>
        This will generate an error, because myNumbers[10] does not exist.
        <pre>
        public class Main {
          public static void main(String[ ] args) {
            int[] myNumbers = {1, 2, 3};
            System.out.println(myNumbers[10]); // error!
          }
        }
        The output will be something like this:
        
        Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
                at Main.main(Main.java:4)</pre>
        If an error occurs, we can use try...catch to catch the error and execute some code to handle it:
        <br>
        Example<pre>
        public class Main {
          public static void main(String[ ] args) {
            try {
              int[] myNumbers = {1, 2, 3};
              System.out.println(myNumbers[10]);
            } catch (Exception e) {
              System.out.println("Something went wrong.");
            }
          }
        }
         
         
        The output will be:
        </pre>
        Something went wrong.
        <h2>Finally</h2>
        The finally statement lets you execute code, after try...catch, regardless of the result:
        <br>
        Example<pre>
        public class Main {
          public static void main(String[] args) {
            try {
              int[] myNumbers = {1, 2, 3};
              System.out.println(myNumbers[10]);
            } catch (Exception e) {
              System.out.println("Something went wrong.");
            } finally {
              System.out.println("The 'try catch' is finished.");
            }
          }
        }
         
        The output will be:
        
        Something went wrong.
        </pre>
        The 'try catch' is finished.
        <h2>The throw keyword</h2>
        The throw statement allows you to create a custom error.
        
        The throw statement is used together with an exception type. There are many exception types available in Java: ArithmeticException, FileNotFoundException, ArrayIndexOutOfBoundsException, SecurityException, etc:
        <br>
        Example
        Throw an exception if age is below 18 (print "Access denied"). If age is 18 or older, print "Access granted":
        <pre>
        public class Main {
          static void checkAge(int age) {
            if (age < 18) {
              throw new ArithmeticException("Access denied - You must be at least 18 years old.");
            }
            else {
              System.out.println("Access granted - You are old enough!");
            }
          }
        
          public static void main(String[] args) {
            checkAge(15); // Set age to 15 (which is below 18...)
          }
        }
         
        The output will be:
        
        Exception in thread "main" java.lang.ArithmeticException: Access denied - You must be at least 18 years old.
                at Main.checkAge(Main.java:4)
                at Main.main(Main.java:12)</pre>
        If age was 20, you would not get an exception:
        
        Example<pre>
        checkAge(20);
        The output will be:
        
        Access granted - You are old enough!</pre></p></section><footer>
    <button id="previous" onclick="window.location.href='intermediatepg21.html'">Previous</button>
    <button id="next" onclick="window.location.href='intermediatepg23.html'">Next</button></footer>
</body>
</html>